# Generated by Django 5.1.1 on 2024-09-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cartmanagementmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmanagementmodels',
            name='add_to_cart',
            field=models.JSONField(default=list),
        ),
    ]
